name: fpdt
description: A collection of functions and monads for functional programming in dart.
version: 0.0.71
homepage: https://github.com/tim-smart/fpdt/tree/main/packages/fpdt

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fast_immutable_collections: any

dev_dependencies:
  flutter_lints: ^1.0.0
  test: any
