name: fpdt_flutter
description: Helpers for using fpdt with flutter.
version: 0.1.1
homepage: https://github.com/tim-smart/fpdt/tree/main/packages/fpdt_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.0 <1.0.0"
  flutter_nucleus: ">=0.0.0 <1.0.0"
  flutter_riverpod: ">=1.0.0 <2.0.0"
  fpdt: any
  freezed_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: any
  build_runner: any
